env:
  test
projectName:
  chinawuliu-trustworthy-cache
spring:
  datasource:
    url: jdbc:mysql://rm-bp106y19fa3992tt9.mysql.rds.aliyuncs.com:3306/tech_cfg_center_mycat_0
    username: cfgcenter_mc_tst
    password: cfgcenter_mc_tst_d290a6
    driverClassName: com.mysql.jdbc.Driver
redisCluster:
  password: cflp1312
  address: 192.168.3.102:6379;192.168.3.103:6379;192.168.3.105:6379
