env:
  prd
projectName:
  chinawuliu-trustworthy-admin
spring:
  datasource:
    url: jdbc:mysql://rm-bp106y19fa3992tt9.mysql.rds.aliyuncs.com:3306
    username: cfgcenter_mc_tst
    password: cfgcenter_mc_tst_d290a6
    driverClassName: com.mysql.jdbc.Driver 
