env:
  test
projectName:
  chinawuliu-trustworthy-admin
spring:
  datasource:
    url: jdbc:mysql://192.168.3.110:3306/trustworthy
    username: admin
    password: cflp.trustworthy
    driverClassName: com.mysql.jdbc.Driver
