env:
  test
projectName:
  chinawuliu-trustworthy-cache
spring:
  datasource:
    url: jdbc:mysql://rm-bp106y19fa3992tt9.mysql.rds.aliyuncs.com:3306/tech_cfg_center_mycat_0
    username: cfgcenter_mc_tst
    password: cfgcenter_mc_tst_d290a6
    driverClassName: com.mysql.jdbc.Driver
redis-cluster:
  192.168.1.3:7001
