env:
  test
projectName:
  chinawuliu-trustworthy-declare
spring:
  datasource:
    url: jdbc:mysql://192.168.3.110:3306/trustworthy?characterEncoding=UTF-8&useSSL=false
    username: admin
    password: cflp.trustworthy
    driverClassName: com.mysql.jdbc.Driver
