env:
  test
projectName:
  chinawuliu-trustworthy-cache
spring:
  datasource:
    url: jdbc:mysql://192.168.3.110:3306/trustworthy
    username: admin
    password: cflp.trustworthy
    driverClassName: com.mysql.jdbc.Driver
redisCluster:
  password: cflp1312
  address: 192.168.3.102:6379;192.168.3.103:6379;192.168.3.105:6379
