env:
  test
projectName:
  chinawuliu-trustworthy-declare
spring:
  datasource:
    url: jdbc:mysql://192.168.3.110:3306/trustworthy?characterEncoding=UTF-8&useSSL=false
    username: admin
    password: cflp.trustworthy
    driverClassName: com.mysql.jdbc.Driver
    
# aliyun config
aliyun: 
  accessKeyId: LTAILMiOXiLVJFUj
  accessKeySecret: BJgQhk5qXInYFLNmNcuB95lN2TuO4U
  sms:
    product: Dysmsapi
    domain: dysmsapi.aliyuncs.com
    signName: 中物联
    registerTempleteCode: SMS_150491805
    loginTempleteCode: SMS_150491807
  oss:
    endpoint: oss-cn-beijing.aliyuncs.com
    bucketName: cflp-cx

# feign 
trustworthy-cache:
  service: chinawuliu-trustworthy-cache
  
# 钛阳 
trustworthy-ti:
  service: zhongan.io
  serviceUrl: https://test.zhongan.io

# OCR
trustworthy-ocr:
  appKey: 
  appSecret: 
  productId: Trustworthy
  channelId: Trustworthy
  token: 96984aee-e743-11e8-b301-00163e0002a7
  service: za-ocr-business
  serviceUrl: 18043-zis-labs-za-ocr-business.test.za.net
